### ISSUE TITLE
Compacted sand and gravel blocks dont drop when destoyed

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Wini#1]
After sand or gravel is compacted the block can then be broken by a normal tool. Currently the blocks wont drop an item when destroyed, which was a decision not a bug.

However do I actually want to make then drop real item, so they can be collected and placed elsewhere?

**Comment by UnPure** [comment]
I think the best idea would be to drop the normal sand and gravel after destroying the compacted versions.

**Comment by Ipsis** [comment]
I like the idea.
I'll probably make it configurable so you can select between:
- compacted block (default)
- uncompacted block

I am going to make sure that something will be dropped.
